Veins Framework: ReadablePacket Class Reference
ReadablePacket Class Reference abstract
#include <bluetoothConnection.hpp>
Public Member Functions
virtual ~ReadablePacket ()
virtual void read (ByteBuffer *)=0
virtual void process (BluetoothConnection *)=0
Protected Member Functions
std::string readString (ByteBuffer *)
Constructor & Destructor Documentation
virtual ReadablePacket::~ReadablePacket () inline virtual
{
     }
Member Function Documentation
virtual void ReadablePacket::process (BluetoothConnection *) pure virtual
Implemented in R_MessagePacket.
Referenced by PacketHandler::processPacket().
virtual void ReadablePacket::read (ByteBuffer *) pure virtual
Implemented in R_MessagePacket.
Referenced by PacketReader::handlerWrapped().
std::string ReadablePacket::readString (ByteBuffer * buf) protected
Referenced by R_MessagePacket::read().
{
     std::string str = "";
     char c;
     while ((c = buf->getChar()) != '\000') {
         str += c;
         std::cout << c;
     }
     std::cout << c << std::endl;
     return str;
 }
The documentation for this class was generated from the following files:
bluetoothConnection.hpp
BluetoothConnection.cc