Veins Framework: PacketReader Class Reference
PacketReader Class Reference abstract
#include <bluetoothConnection.hpp>
Public Member Functions
PacketReader (BluetoothConnection *)
virtual ReadablePacket * createPacket (short)=0
void setPacketListener (PacketListener *)
Static Public Member Functions
static void * handler (void *)
Protected Attributes
BluetoothConnection * con
Private Member Functions
void handlerWrapped ()
void handlerPackets ()
Static Private Member Functions
static void * handlerPacketsWrapped (void *)
Private Attributes
PacketListener * listener
pthread_mutex_t mutex
BlockingQueue * packets
Constructor & Destructor Documentation
PacketReader::PacketReader (BluetoothConnection * con)
{
     this->con = con;
     packets = new BlockingQueue();
     listener = NULL;
     mutex = PTHREAD_MUTEX_INITIALIZER;
 }
Member Function Documentation
virtual ReadablePacket* PacketReader::createPacket (short) pure virtual
Implemented in PacketHandler.
Referenced by handlerWrapped().
void * PacketReader::handler (void * context) static
Referenced by BluetoothConnection::accept().
{
     ((PacketReader*) context)->handlerWrapped();
     return context;
 }
void PacketReader::handlerPackets () private
Referenced by handlerWrapped(), and setPacketListener().
{
     pthread_t thread;
     pthread_create(&thread, NULL, PacketReader::handlerPacketsWrapped,
             (void*) this);
 }
void * PacketReader::handlerPacketsWrapped (void * context) static private
Referenced by handlerPackets().
{
     PacketReader* self = (PacketReader*) context;
     pthread_mutex_lock(&self->mutex);
     {
         while (!self->packets->empty() && self->listener != NULL) {
             self->listener->processPacket(self->packets->pop());
         }
     }
     pthread_mutex_unlock(&self->mutex);
     return context;
 }
void PacketReader::handlerWrapped () private
{
     if(con->mSocket == -1) {
         delete con;
         con = NULL;
         return;
     }
     con->waiting = true;
     con->client = accept(con->mSocket, (struct sockaddr*) &con->remote, &con->opt);
     con->waiting = false;
     if (!con->isConnected())
         return;
     do {
         try {
             ByteBuffer* buf = con->read();
             if (buf == NULL) {
                 if (!con->isConnected()) {
                     return;
                 }
                 continue;
             }
             short opcode = buf->getShort();
             ReadablePacket * packet = createPacket(opcode);
             if (packet != NULL) {
                 packet->read(buf);
                 packets->push(packet);
                 if (listener != NULL) {
                     handlerPackets();
                 }
             }
         } catch (...) {
             std::cout << "error in handler " << std::endl;
             break;
         }
     } while (true);
 }
void PacketReader::setPacketListener (PacketListener * listener)
Referenced by PacketHandler::PacketHandler().
{
     this->listener = listener;
     handlerPackets();
 }
Member Data Documentation
BluetoothConnection* PacketReader::con protected
Referenced by handlerWrapped(), PacketReader(), and PacketHandler::processPacket().
PacketListener* PacketReader::listener private
Referenced by handlerWrapped(), PacketReader(), and setPacketListener().
pthread_mutex_t PacketReader::mutex private
Referenced by PacketReader().
BlockingQueue* PacketReader::packets private
Referenced by handlerWrapped(), and PacketReader().
The documentation for this class was generated from the following files:
bluetoothConnection.hpp
BluetoothConnection.cc