Veins Framework: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <ByteBuffer.h>
Public Member Functions
ByteBuffer (uint32_t size=DEFAULT_SIZE)
ByteBuffer ByteBuffer.cpp Copyright 2011 - 2013 Ramsey Kant.
ByteBuffer (uint8_t *arr, uint32_t size)
ByteBuffer constructor Consume an entire uint8_t array of length len in the ByteBuffer.
virtual ~ByteBuffer ()
ByteBuffer Deconstructor.
uint32_t bytesRemaining ()
Bytes Remaining Returns the number of bytes from the current read position till the end of the buffer.
void clear ()
Clear Clears out all data from the internal vector (original preallocated size remains), resets the positions to 0.
ByteBuffer * clone ()
Clone Allocate an exact copy of the ByteBuffer on the heap and return a pointer.
bool equals (ByteBuffer *other)
Equals, test for data equivilancy Compare this ByteBuffer to another by looking at each byte in the internal buffers and making sure they are the same.
void resize (uint32_t newSize)
Resize Reallocates memory for the internal buffer of size newSize.
uint32_t size ()
Size Returns the size of the internal buffer...not necessarily the length of bytes used as data!
template<typename T >
int32_t find (T key, uint32_t start=0)
void replace (uint8_t key, uint8_t rep, uint32_t start=0, bool firstOccuranceOnly=false)
Replace Replace occurance of a particular uint8_t, key, with the uint8_t rep.
uint8_t peek ()
uint8_t get ()
uint8_t get (uint32_t index)
void getBytes (uint8_t *buf, uint32_t len)
char getChar ()
char getChar (uint32_t index)
double getDouble ()
double getDouble (uint32_t index)
float getFloat ()
float getFloat (uint32_t index)
uint32_t getInt ()
uint32_t getInt (uint32_t index)
uint64_t getLong ()
uint64_t getLong (uint32_t index)
uint16_t getShort ()
uint16_t getShort (uint32_t index)
void put (ByteBuffer *src)
void put (uint8_t b)
void put (uint8_t b, uint32_t index)
void putBytes (uint8_t *b, uint32_t len)
void putBytes (uint8_t *b, uint32_t len, uint32_t index)
void putChar (char value)
void putChar (char value, uint32_t index)
void putDouble (double value)
void putDouble (double value, uint32_t index)
void putFloat (float value)
void putFloat (float value, uint32_t index)
void putInt (uint32_t value)
void putInt (uint32_t value, uint32_t index)
void putLong (uint64_t value)
void putLong (uint64_t value, uint32_t index)
void putShort (uint16_t value)
void putShort (uint16_t value, uint32_t index)
void setReadPos (uint32_t r)
uint32_t getReadPos ()
void setWritePos (uint32_t w)
uint32_t getWritePos ()
void setName (std::string n)
std::string getName ()
void printInfo ()
void printAH ()
void printAscii ()
void printHex ()
void printPosition ()
Private Member Functions
template<typename T >
T read ()
template<typename T >
T read (uint32_t index) const
template<typename T >
void append (T data)
template<typename T >
void insert (T data, uint32_t index)
Private Attributes
uint32_t rpos
uint32_t wpos
std::vector< uint8_t > buf
std::string name
Constructor & Destructor Documentation
ByteBuffer::ByteBuffer (uint32_t size = DEFAULT_SIZE)
ByteBuffer ByteBuffer.cpp Copyright 2011 - 2013 Ramsey Kant.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. ByteBuffer constructor Reserves specified size in internal vector
Parameters
size Size (in bytes) of space to preallocate internally. Default is set in DEFAULT_SIZE
Referenced by clone().
{
         buf.reserve(size);
         clear();
 #ifdef BB_UTILITY
         name = "";
 #endif
 }
ByteBuffer::ByteBuffer (uint8_t * arr, uint32_t size)
ByteBuffer constructor Consume an entire uint8_t array of length len in the ByteBuffer.
Parameters
arr uint8_t array of data (should be of length len)
size Size of space to allocate
{
         // If the provided array is NULL, allocate a blank buffer of the provided size
         if(arr == NULL) {
                 buf.reserve(size);
                 clear();
         } else { // Consume the provided array
                 buf.reserve(size);
                 clear();
                 putBytes(arr, size);
         }
 #ifdef BB_UTILITY
         name = "";
 #endif
 }
ByteBuffer::~ByteBuffer () virtual
ByteBuffer Deconstructor.
{
 }
Member Function Documentation
template<typename T > void ByteBuffer::append (T data) inline private
{
                 uint32_t s = sizeof(data);
                 if (size() < (wpos + s))
                         buf.resize(wpos + s);
                 memcpy(&buf[wpos], (uint8_t*)&data, s);
                 //printf("writing %c to %i\n", (uint8_t)data, wpos);
                 wpos += s;
         }
uint32_t ByteBuffer::bytesRemaining ()
Bytes Remaining Returns the number of bytes from the current read position till the end of the buffer.
Returns
Number of bytes from rpos to the end (size())
{
         return size()-rpos;
 }
void ByteBuffer::clear ()
Clear Clears out all data from the internal vector (original preallocated size remains), resets the positions to 0.
Referenced by ByteBuffer(), BluetoothConnection::read(), and BluetoothConnection::sendPacket().
{
         rpos = 0;
         wpos = 0;
         buf.clear();
 }
ByteBuffer * ByteBuffer::clone ()
Clone Allocate an exact copy of the ByteBuffer on the heap and return a pointer.
Returns
A pointer to the newly cloned ByteBuffer. NULL if no more memory available
Referenced by BluetoothConnection::read().
{
         ByteBuffer* ret = new ByteBuffer(buf.size());
         // Copy data
         for(uint32_t i = 0; i < buf.size(); i++) {
                 ret->put((uint8_t)get(i));
         }
         // Reset positions
         ret->setReadPos(getReadPos());
         ret->setWritePos(getWritePos());
         return ret;
 }
bool ByteBuffer::equals (ByteBuffer * other)
Equals, test for data equivilancy Compare this ByteBuffer to another by looking at each byte in the internal buffers and making sure they are the same.
Parameters
other A pointer to a ByteBuffer to compare to this one
Returns
True if the internal buffers match. False if otherwise
{
         // If sizes aren't equal, they can't be equal
         if(size() != other->size())
                 return false;
         // Compare byte by byte
         uint32_t len = size();
         for(uint32_t i = 0; i < len; i++) {
                 if((uint8_t)get(i) != (uint8_t)other->get(i))
                         return false;
         }
         return true;
 }
template<typename T > int32_t ByteBuffer::find (T key, uint32_t start = 0) inline
{
         int32_t ret = -1;
         uint32_t len = buf.size();
         for(uint32_t i = start; i < len; i++) {
             T data = read<T>(i);
             // Wasn't actually found, bounds of buffer were exceeded
             if((key != 0) && (data == 0))
                 break;
             // Key was found in array
             if(data == key) {
                 ret = (int32_t)i;
                 break;
             }
         }
         return ret;
     }
uint8_t ByteBuffer::get ()
Referenced by equals(), and put().
{
         return read<uint8_t>();
 }
uint8_t ByteBuffer::get (uint32_t index)
{
         return read<uint8_t>(index);
 }
void ByteBuffer::getBytes (uint8_t * buf, uint32_t len)
Referenced by BluetoothConnection::write().
{
         for(uint32_t i = 0; i < len; i++) {
                 buf[i] = read<uint8_t>();
         }
 }
char ByteBuffer::getChar ()
Referenced by ReadablePacket::readString().
{
         return read<uint16_t>();
 }
char ByteBuffer::getChar (uint32_t index)
{
         return read<char>(index);
 }
double ByteBuffer::getDouble ()
{
         return read<double>();
 }
double ByteBuffer::getDouble (uint32_t index)
{
         return read<double>(index);
 }
float ByteBuffer::getFloat ()
{
         return read<float>();
 }
float ByteBuffer::getFloat (uint32_t index)
{
         return read<float>(index);
 }
uint32_t ByteBuffer::getInt ()
{
         return read<uint32_t>();
 }
uint32_t ByteBuffer::getInt (uint32_t index)
{
         return read<uint32_t>(index);
 }
uint64_t ByteBuffer::getLong ()
{
         return read<uint64_t>();
 }
uint64_t ByteBuffer::getLong (uint32_t index)
{
         return read<uint64_t>(index);
 }
std::string ByteBuffer::getName ()
{
         return name;
 }
uint32_t ByteBuffer::getReadPos () inline
Referenced by clone().
{
                 return rpos;
         }
uint16_t ByteBuffer::getShort ()
Referenced by PacketReader::handlerWrapped(), BluetoothConnection::read(), and BluetoothConnection::write().
{
         return read<uint16_t>();
 }
uint16_t ByteBuffer::getShort (uint32_t index)
{
         return read<uint16_t>(index);
 }
uint32_t ByteBuffer::getWritePos () inline
Referenced by clone(), BluetoothConnection::read(), and BluetoothConnection::sendPacket().
{
                 return wpos;
         }
template<typename T > void ByteBuffer::insert (T data, uint32_t index) inline private
{
                 if((index + sizeof(data)) > size())
                         return;
                 memcpy(&buf[index], (uint8_t*)&data, sizeof(data));
                 wpos = index+sizeof(data);
         }
uint8_t ByteBuffer::peek ()
{
         return read<uint8_t>(rpos);
 }
void ByteBuffer::printAH ()
{
         uint32_t length = buf.size();
         std::cout << "ByteBuffer " << name.c_str() << " Length: " << length << ". ASCII & Hex Print" << std::endl;
         for(uint32_t i = 0; i < length; i++) {
                 printf("0x%02x ", buf[i]);
         }
         printf("\n");
         for(uint32_t i = 0; i < length; i++) {
                 printf("%c ", buf[i]);
         }
         printf("\n");
 }
void ByteBuffer::printAscii ()
{
         uint32_t length = buf.size();
         std::cout << "ByteBuffer " << name.c_str() << " Length: " << length << ". ASCII Print" << std::endl;
         for(uint32_t i = 0; i < length; i++) {
                 printf("%c ", buf[i]);
         }
         printf("\n");
 }
void ByteBuffer::printHex ()
{
         uint32_t length = buf.size();
         std::cout << "ByteBuffer " << name.c_str() << " Length: " << length << ". Hex Print" << std::endl;
         for(uint32_t i = 0; i < length; i++) {
                 printf("0x%02x ", buf[i]);
         }
         printf("\n");
 }
void ByteBuffer::printInfo ()
{
         uint32_t length = buf.size();
         std::cout << "ByteBuffer " << name.c_str() << " Length: " << length << ". Info Print" << std::endl;
 }
void ByteBuffer::printPosition ()
{
         uint32_t length = buf.size();
         std::cout << "ByteBuffer " << name.c_str() << " Length: " << length << " Read Pos: " << rpos << ". Write Pos: " << wpos << std::endl;
 }
void ByteBuffer::put (ByteBuffer * src)
Referenced by clone(), and W_MessagePacket::write().
{
         uint32_t len = src->size();
         for(uint32_t i = 0; i < len; i++)
                 append<uint8_t>(src->get(i));
 }
void ByteBuffer::put (uint8_t b)
{
         append<uint8_t>(b);
 }
void ByteBuffer::put (uint8_t b, uint32_t index)
{
         insert<uint8_t>(b, index);
 }
void ByteBuffer::putBytes (uint8_t * b, uint32_t len)
Referenced by ByteBuffer(), and BluetoothConnection::read().
{
         // Insert the data one byte at a time into the internal buffer at position i+starting index
         for(uint32_t i = 0; i < len; i++)
                 append<uint8_t>(b[i]);
 }
void ByteBuffer::putBytes (uint8_t * b, uint32_t len, uint32_t index)
{
         wpos = index;
         // Insert the data one byte at a time into the internal buffer at position i+starting index
         for(uint32_t i = 0; i < len; i++)
                 append<uint8_t>(b[i]);
 }
void ByteBuffer::putChar (char value)
Referenced by W_MessagePacket::write(), and WriteblePacket::writeString().
{
         append<uint16_t>(value);
 }
void ByteBuffer::putChar (char value, uint32_t index)
{
         insert<char>(value, index);
 }
void ByteBuffer::putDouble (double value)
Referenced by W_MessagePacket::write(), and W_WSMPacket::write().
{
         append<double>(value);
 }
void ByteBuffer::putDouble (double value, uint32_t index)
{
         insert<double>(value, index);
 }
void ByteBuffer::putFloat (float value)
Referenced by W_MessagePacket::write().
{
         append<float>(value);
 }
void ByteBuffer::putFloat (float value, uint32_t index)
{
         insert<float>(value, index);
 }
void ByteBuffer::putInt (uint32_t value)
Referenced by W_MessagePacket::write(), and W_WSMPacket::write().
{
         append<uint32_t>(value);
 }
void ByteBuffer::putInt (uint32_t value, uint32_t index)
{
         insert<uint32_t>(value, index);
 }
void ByteBuffer::putLong (uint64_t value)
Referenced by W_MessagePacket::write().
{
         append<uint64_t>(value);
 }
void ByteBuffer::putLong (uint64_t value, uint32_t index)
{
         insert<uint64_t>(value, index);
 }
void ByteBuffer::putShort (uint16_t value)
Referenced by BluetoothConnection::sendPacket(), W_MessagePacket::write(), and W_WSMPacket::write().
{
         append<uint16_t>(value);
 }
void ByteBuffer::putShort (uint16_t value, uint32_t index)
{
         insert<uint16_t>(value, index);
 }
template<typename T > T ByteBuffer::read () inline private
{
                 T data = read<T>(rpos);
                 rpos += sizeof(T);
                 return data;
         }
template<typename T > T ByteBuffer::read (uint32_t index) const inline private
{
                 if(index + sizeof(T) <= buf.size())
                         return *((T*)&buf[index]);
                 return 0;
         }
void ByteBuffer::replace (uint8_t key, uint8_t rep, uint32_t start = 0, bool firstOccuranceOnly = false)
Replace Replace occurance of a particular uint8_t, key, with the uint8_t rep.
Parameters
key uint8_t to find for replacement
rep uint8_t to replace the found key with
start Index to start from. By default, start is 0
firstOccuranceOnly If true, only replace the first occurance of the key. If false, replace all occurances. False by default
{
     uint32_t len = buf.size();
     for(uint32_t i = start; i < len; i++) {
         uint8_t data = read<uint8_t>(i);
         // Wasn't actually found, bounds of buffer were exceeded
         if((key != 0) && (data == 0))
             break;
         // Key was found in array, perform replacement
         if(data == key) {
             buf[i] = rep;
             if(firstOccuranceOnly)
                 return;
         }
     }
 }
void ByteBuffer::resize (uint32_t newSize)
Resize Reallocates memory for the internal buffer of size newSize.
Read and write positions will also be reset
Parameters
newSize The amount of memory to allocate
{
         buf.resize(newSize);
         rpos = 0;
         wpos = 0;
 }
void ByteBuffer::setName (std::string n)
{
         name = n;
 }
void ByteBuffer::setReadPos (uint32_t r) inline
Referenced by clone(), and BluetoothConnection::write().
{
                 rpos = r;
         }
void ByteBuffer::setWritePos (uint32_t w) inline
Referenced by clone(), and BluetoothConnection::sendPacket().
{
                 wpos = w;
         }
uint32_t ByteBuffer::size ()
Size Returns the size of the internal buffer...not necessarily the length of bytes used as data!
Returns
size of the internal buffer
Referenced by append(), bytesRemaining(), equals(), insert(), and put().
{
         return buf.size();
 }
Member Data Documentation
std::vector<uint8_t> ByteBuffer::buf private
Referenced by append(), ByteBuffer(), clear(), clone(), find(), insert(), printAH(), printAscii(), printHex(), printInfo(), printPosition(), read(), replace(), resize(), and size().
std::string ByteBuffer::name private
Referenced by ByteBuffer(), getName(), printAH(), printAscii(), printHex(), printInfo(), printPosition(), and setName().
uint32_t ByteBuffer::rpos private
Referenced by bytesRemaining(), clear(), getReadPos(), peek(), printPosition(), read(), resize(), and setReadPos().
uint32_t ByteBuffer::wpos private
Referenced by append(), clear(), getWritePos(), insert(), printPosition(), putBytes(), resize(), and setWritePos().
The documentation for this class was generated from the following files:
ByteBuffer.h
ByteBuffer.cc