Veins Framework: WriteblePacket Class Reference
WriteblePacket Class Reference abstract
#include <bluetoothConnection.hpp>
Public Member Functions
virtual ~WriteblePacket ()
virtual void write (BluetoothConnection *, ByteBuffer *)=0
short getOpcode ()
Protected Member Functions
void writeString (std::string, ByteBuffer *)
Protected Attributes
short opcode
Constructor & Destructor Documentation
virtual WriteblePacket::~WriteblePacket () inline virtual
{
     }
Member Function Documentation
short WriteblePacket::getOpcode ()
Referenced by BluetoothConnection::sendPacket().
{
     return opcode;
 }
virtual void WriteblePacket::write (BluetoothConnection * , ByteBuffer *) pure virtual
Implemented in W_WSMPacket, and W_MessagePacket.
Referenced by BluetoothConnection::sendPacket().
void WriteblePacket::writeString (std::string msg, ByteBuffer * buf) protected
Referenced by W_MessagePacket::write(), and W_WSMPacket::write().
{
     for (unsigned short i = 0; i < msg.size(); ++i) {
         buf->putChar(msg[i]);
     }
     buf->putChar('\000');
 }
Member Data Documentation
short WriteblePacket::opcode protected
Referenced by getOpcode(), W_MessagePacket::W_MessagePacket(), and W_WSMPacket::W_WSMPacket().
The documentation for this class was generated from the following files:
bluetoothConnection.hpp
BluetoothConnection.cc